spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ecommerce?useSSL=false&serverTimezone=UTC
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 20
    open-in-view: false
  sql:
    init:
      mode: always